export const btnVals = [
  { key: 'C', id: 0 },
  { key: '7', id: 1 },
  { key: '8', id: 2 },
  { key: '9', id: 3 },
  { key: '*', id: 4 },
  { key: '-', id: 5 },
  { key: '4', id: 6 },
  { key: '5', id: 7 },
  { key: '6', id: 8 },
  { key: '\\', id: 9 },
  { key: '+', id: 10 },
  { key: '1', id: 11 },
  { key: '2', id: 12 },
  { key: '3', id: 13 },
  { key: '=', id: 14 },
  { key: '.', id: 15 },
  { key: '(', id: 16 },
  { key: '0', id: 17 },
  { key: ')', id: 18 },
  { key: 'CE', id: 19 },
]
